spring.application.name=collegeHelpDeskPro

# 🔥 Cloud MongoDB Connection (Direct string)
spring.data.mongodb.uri=mongodb+srv://aditya:aditya@cluster0.guomznc.mongodb.net/collegeHelpDeskPro?retryWrites=true&w=majority&appName=Cluster0

# 🔥 Dynamic Port for Cloud Platforms (Render assigns a random port)
server.port=${PORT:8080}

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=adityasaini472894@gmail.com
# ⚠️ WARNING: Tera password yahan hardcoded hai. 
# Project submit hone ke baad is App Password ko apne Google Account se delete zaroor kar dena!
spring.mail.password=ccegweixoymtbgll
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Fixed typo here (loggin -> logging)
logging.level.org.springframework.security=DEBUG